### ISSUE TITLE
Motiviation?

### ISSUE THREAD

**Issue by KATT** [use-form/use-form#37]
Hey! 

I just stumbled on this and I'm curious about the motivation of creating use-form instead of some of the existing and already quite great alternatives like react-hook-form & final-form? 

What are the key differences from react-hook-form? API looks quite similar

**Comment by Jucian0** [comment]
Hey, thanks for asking, when I started this repository, these options were not very helpful than now, so I know that today there are no many advantages or differences.
I wrote a post about it here: https://dev.to/jucian0/building-forms-with-useform-1cna

**Comment by KATT** [comment]
Okay, thanks for answering! 😊
